# 
policy_path: "{LEGGED_GYM_ROOT_DIR}/logs/rough_go2/exported/policies/policy_1.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/go2/xml/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [20, 20, 20, 20, 20,  20, 20, 20, 20, 20, 20,20]
kds: [0.5, 0.5, 0.5, 0.5, 0.5,  0.5, 0.5, 0.5, 0.5, 0.5,0.5,0.5]
# Format: [FL_hip, FL_thigh, FL_calf, FR_hip, FR_thigh, FR_calf, RL_hip, RL_thigh, RL_calf,  RR_hip, RR_thigh, RR_calf] xml文件
default_angles: [0.1,  0.8,  -1.5,  -0.1, 0.8,
                -1.5,  0.1,  1,  -1.5, -0.1 , 1, -1.5]


# Scaling factors for observations and actions
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
# Command scaling factors (linear_x, linear_y, angular_yaw)
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 45

cmd_init: [-0.8, 0, 0]
