# 
policy_path: "{LEGGED_GYM_ROOT_DIR}/logs/tinymal/exported/policies/policy_1.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/tinymal/xml/tinymal.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [3.3, 3.3, 3.3, 3.3, 3.3,  3.3, 3.3, 3.3, 3.3, 3.3, 3.3,3.3]
kds: [0.25, 0.25, 0.25, 0.25, 0.25,  0.25, 0.25, 0.25, 0.25, 0.25,0.25,0.25]
# Format: [LF_hip, LF_thigh, LF_calf, LH_hip, LH_thigh, LH_calf, RF_hip, RF_thigh, RF_calf, RH_hip, RH_thigh, RH_calf] xml文件
default_angles: [-0.20,  0.9,  -1.55,  0.2, -0.9,
                1.55,  0.2,  0.9,  -1.55, -0.2 , -0.9, 1.55]


# Scaling factors for observations and actions
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
# Command scaling factors (linear_x, linear_y, angular_yaw)
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 45

cmd_init: [0.6, 0.0, -0.0]